project:
  type: book
  output-dir: ../docs
  
book:
  title: "Introductory Economic Statistics: A Data-Driven Approach using R"
  author: "Jordan Adamson"
  reader-mode: true
  date: last-modified
  date-format: "DD.MM.YYYY"
  chapters:
    - index.qmd
    - part: 00_00_GettingStarted.qmd
      chapters:
        - 00_01_FirstSteps.qmd
    - part: 01_00_UnivariateData.qmd
      chapters:
        - 01_02_Data.qmd
        - 01_03_DescriptiveStatistics.qmd
        - 01_04_RandomVariables.qmd
        - 01_05_Sampling.qmd
        - 01_06_PopStatistics.qmd
        - 01_07_Intervals.qmd
        - 01_08_HypothesisTests.qmd
        - 01_09_MiscTopics.qmd
    - part: 02_00_BivariateData.qmd
      chapters:
        - 02_10_BivariateDistributions.qmd
        - 02_11_ComparingGroups.qmd
        - 02_12_Associations.qmd
        - 02_13_SimpleRegression.qmd
        - 02_14_LocalRegression.qmd
        - 02_15_InferencePrediction.qmd
        - 02_16_BivariateProbability.qmd
        - 02_17_StatisticalTheory.qmd
        - 02_17_DataAnalysis.qmd
    - part: 03_00_MultivariateData.qmd
      chapters:
        - 03_18_MultipleRegression.qmd
        - 03_19_InterpretingRegression.qmd
        - 03_20_Regressograms.qmd
        - 03_21_ObservationalData.qmd
        - 03_22_ExperimentalData.qmd
        - 03_23_DataScientism.qmd
        - 03_24_MiscTopics.qmd
  page-navigation: true
  repo-url: https://github.com/Jadamso/Rbooks/
  repo-branch: main
  site-url: https://jadamso.github.io/Rbooks/
  cover-image: Figures_Manual/Logo.png
  favicon: Figures_Manual/Logo.png
  sidebar:
    style: "docked"

  
bibliography: references.bib
lang: en

comments:
  hypothesis: false

format:
  html:
    theme: default
    highlight-style: arrow
    code-fold: true
    toc: false
    section-divs: true
    toc-location: left
    resources:
      - Figures_Manual/**

execute:
  echo: true
  warning: false
  message: false
  freeze: auto # cache; stabilizes builds

knitr:
  opts_chunk:
    collapse: true
    prompt: false
