project:
  type: book
  output-dir: ../docs
  
book:
  title: "Introductory Economic Statistics: A Data-Driven Approach using R"
  author: "Jordan Adamson"
  reader-mode: true
  date: last-modified
  date-format: "DD.MM.YYYY"
  chapters:
    - index.qmd
    - part: 00-00-GettingStarted.qmd
      chapters:
        - 00_01_FirstSteps.qmd
    - part: 01-00-UnivariateData.qmd
      chapters:
        - 01_02_Data.qmd
        - 01_03_DescriptiveStatistics.qmd
        - 01_04_Sampling.qmd
        - 01_05_RandomVariables.qmd
        - 01_06_PopStatistics.qmd
        - 01_07_Intervals.qmd
        - 01_08_HypothesisTests.qmd
        - 01_09_MiscTopics.qmd
    - part: 02-00-BivariateData.qmd
      chapters: 
        - 02_10_BivariateDistributions.qmd
        - 02_11_BivariateStatistics.qmd
        - 02_12_ComparingGroups.qmd
        - 02_13_SimpleRegression.qmd
        - 02_14_LocalRegression.qmd
        - 02_15_DataAnalysis.qmd
        - 02_16_MiscTopics.qmd
    - part: 03-00-MultivariateData.qmd
      chapters:         
        - 03_17_IntermediateRegression.qmd
        - 03_18_InterprettingRegression.qmd
        - 03_19_ObservationalData.qmd
        - 03_20_ExperimentalData.qmd
        - 03_21_DataScientism.qmd
        - 03_22_MiscTopics.qmd
  page-navigation: true
  repo-url: https://github.com/Jadamso/Rbooks/
  repo-branch: main
  site-url: https://jadamso.github.io/Rbooks/
  cover-image: Figures_Manual/Logo.png
  favicon: Figures_Manual/Logo.png
  sidebar:
    style: "docked"

  
bibliography: references.bib
lang: en

comments:
  hypothesis: true

format:
  html:
    theme: default
    highlight-style: arrow
    code-fold: true
    toc: false
    toc-location: left


execute:
  echo: true
  warning: false
  message: false
  freeze: auto # cache; stabilizes builds

knitr:
  opts_chunk:
    collapse: true
    prompt: false
